hypervolt {
  env = "local"
  env = ${?HYPERVOLT_ENV}

  database {
    host = "localhost"
    host = ${?CONDUIT_DB_HOST}
    port = 5532
    port = ${?CONDUIT_DB_PORT}
    database = "conduit"
    database = ${?CONDUIT_DB_DATABASE}
    user = "conduit"
    user = ${?CONDUIT_DB_USER}
    password = "conduit"
    password = ${?CONDUIT_DB_PASSWORD}
  }

  http {
    host = "0.0.0.0"
    host = ${?CONDUIT_HTTP_HOST}
    port = 8080
    port = ${?CONDUIT_HTTP_PORT}
  }

  admin {
    port = 9990
    port = ${?CONDUIT_ADMIN_PORT}
  }

  pulsar {
    service_url = "pulsar://localhost:6650"
    service_url = ${?CONDUIT_PULSAR_URL}
  }

  xero {
    client_id = ""
    client_id = ${?XERO_CLIENT_ID}
    client_secret = ""
    client_secret = ${?XERO_CLIENT_SECRET}
    identity_url = "https://identity.xero.com"
    identity_url = ${?XERO_IDENTITY_URL}
    api_url = "https://api.xero.com/api.xro/2.0"
    api_url = ${?XERO_API_URL}
    tenant_id = ""
    tenant_id = ${?XERO_TENANT_ID}
    scope = "accounting.transactions accounting.contacts"
    scope = ${?XERO_SCOPE}
  }
}
