hypervolt {
  env = "local"
  env = ${?HYPERVOLT_ENV}

  database {
    host = "localhost"
    host = ${?CONDUIT_DB_HOST}
    port = 5532
    port = ${?CONDUIT_DB_PORT}
    database = "conduit"
    database = ${?CONDUIT_DB_DATABASE}
    user = "conduit"
    user = ${?CONDUIT_DB_USER}
    password = "conduit"
    password = ${?CONDUIT_DB_PASSWORD}
  }

  http {
    host = "0.0.0.0"
    host = ${?CONDUIT_HTTP_HOST}
    port = 8080
    port = ${?CONDUIT_HTTP_PORT}
  }

  admin {
    port = 9990
    port = ${?CONDUIT_ADMIN_PORT}
  }
}
